@startuml
hide time-axis
concise "without gaps" as V
concise "with gaps" as G
concise "with start" as S
concise "with end" as E
concise "with borders" as B
concise "with start and gaps" as SG
concise "with end and gaps" as EG
concise "with borders and gaps" as BG

V is self
G is self
S is {-}
E is self
B is {-}
SG is {-}
EG is self
BG is {-}

@V
0 is other

@G
0 is {-}
1 is other

@S
0 is self
1 is other

@E
1 is other
2 is {-}

@B
0 is self
1 is other
2 is {-}

@SG
0 is self
1 is {-}
2 is other

@EG
1 is {-}
2 is other
3 is {-}

@BG
0 is self
1 is {-}
2 is other
3 is {-}

@enduml
